package com.watchalign.mobile;

/**
 * GENERATED by tools/research/alpha96_calibration/gen_alpha99_constants.py - do not edit by hand.
 * Single-photo measurement uncertainty per feature family: the pooled within-watch standard deviation over
 * genuine physical watches photographed two or more times (no replica or test photo involved). Source:
 * measurement_uncertainty.py -> alpha99_uncertainty.properties, results/alpha99/uncertainty.md.
 * *_R in dial radii, *_PX in pixels (positional families: the app uses max(sigma_R, sigma_PX / photo R)), *_DEG in
 * degrees. K_SIGMA: a reading beyond the genuine maximum is a clear finding only when the excess exceeds K sigma.
 */
final class Alpha99Uncertainty {
    private Alpha99Uncertainty(){}
    static final double K_SIGMA=3.0;
    /** 20 genuine watches. */
    static final double DATE_TILT_DEG=0.148998;
    /** 19 genuine watches. */
    static final double DATE_TILT_DEGR=119.817161;
    /** 8 genuine watches. */
    static final double NINE_OFF_R=0.000897;
    /** 8 genuine watches. */
    static final double NINE_OFF_PX=0.197582;
    /** 8 genuine watches. */
    static final double NINE_ROT_DEG=0.205383;
    /** 8 genuine watches. */
    static final double NINE_ROT_DEGR=43.434971;
    /** 9 genuine watches. */
    static final double RING_ROT_DEG=0.023854;
    /** 9 genuine watches. */
    static final double RING_ROT_DEGR=7.908438;
    /** 9 genuine watches. */
    static final double RING_SHIFT_R=0.000592;
    /** 9 genuine watches. */
    static final double RING_SHIFT_PX=0.319598;
    /** 9 genuine watches. */
    static final double ROUNDS_OFF_R=0.000573;
    /** 9 genuine watches. */
    static final double ROUNDS_OFF_PX=0.112675;
    /** 9 genuine watches. */
    static final double SIX_OFF_R=0.001246;
    /** 9 genuine watches. */
    static final double SIX_OFF_PX=0.250860;
    /** 9 genuine watches. */
    static final double SIX_ROT_DEG=0.194996;
    /** 9 genuine watches. */
    static final double SIX_ROT_DEGR=45.340069;
    /** 9 genuine watches. */
    static final double TWELVE_CENTRELINE_DEG=0.184105;
    /** 9 genuine watches. */
    static final double TWELVE_CENTRELINE_DEGR=72.582101;
    /** 9 genuine watches. */
    static final double TWELVE_LATERAL_R=0.002019;
    /** 9 genuine watches. */
    static final double TWELVE_LATERAL_PX=0.412108;
    /** 9 genuine watches. */
    static final double TWELVE_SIDES_DEG=0.486607;
    /** 9 genuine watches. */
    static final double TWELVE_SIDES_DEGR=82.765016;
}
