package com.watchalign.mobile;

import android.Manifest;import android.app.Activity;import android.content.pm.PackageManager;import android.graphics.Bitmap;import android.graphics.Color;import android.graphics.SurfaceTexture;import android.hardware.camera2.*;import android.os.Bundle;import android.os.Handler;import android.os.HandlerThread;import android.view.*;import android.widget.*;import java.util.Collections;

/** Camera2 capture with live local quality guidance and an explicit manual override. */
public final class CaptureActivity extends Activity implements TextureView.SurfaceTextureListener {
    private static final int CAMERA_PERMISSION=44;private TextureView preview;private CaptureGuideView guide;private TextView status;private Button capture;private CameraDevice camera;private CameraCaptureSession session;private HandlerThread thread;private Handler handler;private volatile boolean analysing;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA_PERMISSION);}
    private View ui(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);preview=new TextureView(this);preview.setSurfaceTextureListener(this);root.addView(preview,new FrameLayout.LayoutParams(-1,-1));guide=new CaptureGuideView(this);root.addView(guide,new FrameLayout.LayoutParams(-1,-1));LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);controls.setGravity(Gravity.CENTER);controls.setPadding(18,12,18,20);controls.setBackgroundColor(0xCC08111F);status=new TextView(this);status.setText("Centre the full dial inside the guide");status.setTextColor(Color.WHITE);status.setTextSize(17);status.setGravity(Gravity.CENTER);controls.addView(status,new LinearLayout.LayoutParams(-1,64));capture=new Button(this);capture.setText("Capture anyway");capture.setAllCaps(false);capture.setOnClickListener(v->captureFrame());controls.addView(capture,new LinearLayout.LayoutParams(-1,58));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,150,Gravity.BOTTOM);root.addView(controls,cp);return root;}
    @Override protected void onResume(){super.onResume();thread=new HandlerThread("capture");thread.start();handler=new Handler(thread.getLooper());if(preview.isAvailable())openCamera();}
    @Override protected void onPause(){closeCamera();if(thread!=null)thread.quitSafely();thread=null;handler=null;super.onPause();}
    private void openCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)return;try{CameraManager m=(CameraManager)getSystemService(CAMERA_SERVICE);String chosen=null;for(String id:m.getCameraIdList()){Integer facing=m.getCameraCharacteristics(id).get(CameraCharacteristics.LENS_FACING);if(facing!=null&&facing==CameraCharacteristics.LENS_FACING_BACK){chosen=id;break;}}if(chosen==null)return;m.openCamera(chosen,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;startPreview();}public void onDisconnected(CameraDevice c){c.close();}public void onError(CameraDevice c,int e){c.close();runOnUiThread(()->status.setText("Camera unavailable"));}},handler);}catch(Exception e){status.setText("Camera unavailable: "+e.getMessage());}}
    private void startPreview(){try{SurfaceTexture t=preview.getSurfaceTexture();t.setDefaultBufferSize(1280,960);Surface surface=new Surface(t);CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);b.addTarget(surface);b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);camera.createCaptureSession(Collections.singletonList(surface),new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;try{s.setRepeatingRequest(b.build(),null,handler);handler.post(analyseLoop);}catch(Exception ignored){}}public void onConfigureFailed(CameraCaptureSession s){status.setText("Camera preview unavailable");}},handler);}catch(Exception e){status.setText("Camera preview unavailable");}}
    private final Runnable analyseLoop=new Runnable(){public void run(){if(handler==null)return;if(!analysing&&preview.isAvailable()){analysing=true;Bitmap frame=preview.getBitmap(480,480);if(frame!=null)try{CaptureQualityAnalyzer.Result r=CaptureQualityAnalyzer.analyse(frame);runOnUiThread(()->{status.setText(r.guidance);guide.setReady(r.ready);capture.setText(r.ready?"Capture":"Capture anyway");});}catch(Throwable ignored){}finally{frame.recycle();analysing=false;}}handler.postDelayed(this,650);}};
    private void captureFrame(){Bitmap b=preview.getBitmap();if(b==null)return;InspectionImageStore.setCaptured(b.copy(Bitmap.Config.ARGB_8888,false));b.recycle();setResult(RESULT_OK);finish();}
    private void closeCamera(){if(session!=null)session.close();session=null;if(camera!=null)camera.close();camera=null;}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==CAMERA_PERMISSION&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&preview.isAvailable())openCamera();else if(r==CAMERA_PERMISSION)finish();}
    public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){openCamera();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}
}
