package com.watchalign.mobile;

import android.content.Context;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.graphics.PointF;import org.json.JSONArray;import org.json.JSONObject;import java.io.*;import java.util.*;

/** Local-only inspection persistence. Photos and corrected geometry remain in app storage. */
final class InspectionHistory {
 static final class Record {final String id,model,summary,imagePath;final long createdAt;final float[] anchors,points,metrics;Record(String i,String m,long c,String s,String p,float[]a,float[]q,float[]v){id=i;model=m;createdAt=c;summary=s;imagePath=p;anchors=a;points=q;metrics=v;}}
 static Record save(Context c,Bitmap image,String model,PerspectiveMasterRenderer.Pose pose,PointF[] points,Triangle12RelationalMetric.Result metric,String summary)throws Exception{String id=Long.toString(System.currentTimeMillis());File dir=new File(c.getFilesDir(),"inspections");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Cannot create history folder");File photo=new File(dir,id+".jpg");try(FileOutputStream out=new FileOutputStream(photo)){image.compress(Bitmap.CompressFormat.JPEG,94,out);}Record r=new Record(id,model,System.currentTimeMillis(),summary,photo.getAbsolutePath(),poseArray(pose),pointArray(points),new float[]{metric.baseGapRatio,metric.apexGapRatio,metric.heightRatio,metric.rotationDeg,metric.lateralPx});List<Record> all=list(c);all.add(0,r);write(c,all);return r;}
 static List<Record> list(Context c){List<Record> out=new ArrayList<>();File f=index(c);if(!f.exists())return out;try{StringBuilder s=new StringBuilder();try(BufferedReader br=new BufferedReader(new FileReader(f))){String line;while((line=br.readLine())!=null)s.append(line);}JSONArray a=new JSONArray(s.toString());for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);out.add(new Record(o.getString("id"),o.getString("model"),o.getLong("createdAt"),o.getString("summary"),o.getString("imagePath"),floats(o.getJSONArray("anchors")),floats(o.getJSONArray("points")),floats(o.getJSONArray("metrics"))));}}catch(Exception ignored){}return out;}
 static boolean reopen(Record r){Bitmap b=BitmapFactory.decodeFile(r.imagePath);if(b==null||r.anchors.length<10||r.points.length<10||r.metrics.length<5)return false;PerspectiveMasterRenderer.Pose p=new PerspectiveMasterRenderer.Pose();p.anchorMode=true;p.perspectiveMode=true;p.anchor12X=r.anchors[0];p.anchor12Y=r.anchors[1];p.anchor3X=r.anchors[2];p.anchor3Y=r.anchors[3];p.anchor6X=r.anchors[4];p.anchor6Y=r.anchors[5];p.anchor9X=r.anchors[6];p.anchor9Y=r.anchors[7];p.centerX=r.anchors[8];p.centerY=r.anchors[9];PointF[] q=new PointF[5];for(int i=0;i<5;i++)q[i]=new PointF(r.points[i*2],r.points[i*2+1]);Triangle12RelationalMetric.Result m=new Triangle12RelationalMetric.Result(r.metrics[0],r.metrics[1],r.metrics[2],r.metrics[3],r.metrics[4]);InspectionImageStore.baseBitmap=b;InspectionImageStore.alignedPose=p;InspectionImageStore.alignedModelRef=r.model;InspectionImageStore.setTriangleResult(q,m);return true;}
 private static float[] poseArray(PerspectiveMasterRenderer.Pose p){return new float[]{p.anchor12X,p.anchor12Y,p.anchor3X,p.anchor3Y,p.anchor6X,p.anchor6Y,p.anchor9X,p.anchor9Y,p.centerX,p.centerY};}private static float[] pointArray(PointF[] p){float[]a=new float[10];for(int i=0;i<5;i++){a[i*2]=p[i].x;a[i*2+1]=p[i].y;}return a;}private static float[] floats(JSONArray a)throws Exception{float[]v=new float[a.length()];for(int i=0;i<v.length;i++)v[i]=(float)a.getDouble(i);return v;}private static JSONArray json(float[]v){JSONArray a=new JSONArray();for(float x:v)a.put(x);return a;}
 private static void write(Context c,List<Record> all)throws Exception{JSONArray a=new JSONArray();for(Record r:all){JSONObject o=new JSONObject();o.put("id",r.id);o.put("model",r.model);o.put("createdAt",r.createdAt);o.put("summary",r.summary);o.put("imagePath",r.imagePath);o.put("anchors",json(r.anchors));o.put("points",json(r.points));o.put("metrics",json(r.metrics));a.put(o);}try(FileWriter w=new FileWriter(index(c))){w.write(a.toString());}}
 private static File index(Context c){return new File(c.getFilesDir(),"inspection-history.json");}private InspectionHistory(){}
}
