package com.watchalign.mobile;

import android.graphics.Bitmap;import com.watchalign.mobile.qc.QcModuleResult;import org.opencv.android.Utils;import org.opencv.core.Mat;import org.opencv.core.MatOfPoint;import org.opencv.core.Point;import org.opencv.core.Rect;import org.opencv.core.Size;import org.opencv.imgproc.Imgproc;import org.opencv.imgproc.Moments;import java.util.ArrayList;import java.util.List;import java.util.Locale;

/** Evidence-sensitive GMT component checks sharing one canonical rectification. */
final class QcExtendedAnalyzer {
    static final String SEL_VISUAL_ONLY="SEL: visual inspection only; no automatic gap score";
    static final class Result {final Bitmap annotated;final String report;Result(Bitmap a,String r){annotated=a;report=r;}}
    private static final class DateAperture {Rect box;double confidence,numeralXPercent,numeralYPercent;boolean numeralAvailable;}
    private QcExtendedAnalyzer(){}
    static Result analyse(Bitmap watch,String modelRef){return unavailable(watch,"Extended GMT checks require the corrected 12/3/6/9 rectification pose.");}
    static Result analyse(Bitmap watch,Bitmap reference,String modelRef){return analyse(watch,reference,modelRef,InspectionImageStore.alignedPose);}
    static Result analyse(Bitmap watch,Bitmap reference,String modelRef,PerspectiveMasterRenderer.Pose pose){
        CanonicalGmtDial dial=CanonicalGmtDial.create(watch,pose);if(dial==null)return unavailable(watch,"Canonical rectified dial could not be created.");
        try{return analyse(watch,reference,modelRef,dial);}finally{dial.close();}
    }
    static Result analyse(Bitmap watch,Bitmap reference,String modelRef,CanonicalGmtDial dial){
        try{ModelCatalog.Profile profile=ModelCatalog.require(modelRef);StringBuilder report=new StringBuilder("RECTIFICATION\n");for(String e:dial.rectification.evidence())report.append("• ").append(e).append('\n');report.append("\nExtended GMT checks\n");
            GlobalMinuteTrackPhase.Result phase=GlobalMinuteTrackPhase.estimate(dial);if(phase.available)report.append(String.format(Locale.US,"Minute-track phase: %+.2f° · %s component confidence · global 60-position support %.2f.\n",phase.phaseDeg,phase.confidence.name().toLowerCase(Locale.US),phase.support));else report.append("Minute-track phase withheld: ").append(phase.reason).append(". No local tick result is substituted.\n");
            if(profile.hasDate()){DateAperture date=detectDateAperture(watch,dial,profile);if(date==null)report.append("Date aperture withheld: no plausible aperture passed size, aspect, radial-position and orientation gates. Date numeral and cyclops numbers are suppressed.\n");else{QcModuleResult.Confidence dc=cap(confidence(date.confidence),dial.rectification.confidence());report.append("Date aperture: isolated with ").append(dc.name().toLowerCase(Locale.US)).append(" component confidence.\n");if(date.numeralAvailable)report.append(String.format(Locale.US,"Date numeral centring in observed aperture: horizontal %+.1f%%, vertical %+.1f%% (raw local-image measurement).\n",date.numeralXPercent,date.numeralYPercent));else report.append("Date numeral centring withheld: numeral ink was not isolated confidently inside the observed aperture.\n");if(profile.cyclops)report.append("Cyclops: advisory visual inspection only. The dial homography locates the ROI but is not used for refractive fine alignment or magnification claims.\n");}}
            if(profile.rehautCheck)report.append("Rehaut: visual inspection only; engraving visibility is view and focus dependent.\n");if(profile.selCheck)report.append(SEL_VISUAL_ONLY).append('\n');report.append("Lume: unavailable without a dedicated lume image.\n");report.append("Each failed detector withholds only its own component. Raw measurements remain separate from interpretation.\n");report.append("Reference data are image-derived QC evidence, not Rolex factory tolerances and not an authenticity verdict.");return new Result(dial.bitmap(),report.toString());
        }catch(Throwable t){return unavailable(watch,"Extended GMT checks unavailable: "+t.getClass().getSimpleName()+".");}}

    private static DateAperture detectDateAperture(Bitmap source,CanonicalGmtDial dial,ModelCatalog.Profile profile){
        double angle=Math.toRadians(profile.dateHour*30.0);Point expected=dial.sourcePoint(CanonicalGmtDial.CENTER+Math.sin(angle)*CanonicalGmtDial.RADIUS*profile.dateRadiusRatio,CanonicalGmtDial.CENTER-Math.cos(angle)*CanonicalGmtDial.RADIUS*profile.dateRadiusRatio);double scale=(Math.hypot(dial.pose.anchor6X-dial.pose.anchor12X,dial.pose.anchor6Y-dial.pose.anchor12Y)+Math.hypot(dial.pose.anchor9X-dial.pose.anchor3X,dial.pose.anchor9Y-dial.pose.anchor3Y))/4.0;int w=(int)(scale*.48),h=(int)(scale*.34),x=(int)expected.x-w/2,y=(int)expected.y-h/2;x=Math.max(0,x);y=Math.max(0,y);w=Math.min(w,source.getWidth()-x);h=Math.min(h,source.getHeight()-y);if(w<20||h<15)return null;
        Mat rgba=new Mat(),bgr=new Mat(),gray=new Mat(),edges=new Mat(),hierarchy=new Mat();List<MatOfPoint> contours=new ArrayList<>();try{Utils.bitmapToMat(source,rgba);Imgproc.cvtColor(rgba,bgr,Imgproc.COLOR_RGBA2BGR);Rect roi=new Rect(x,y,w,h);Mat sub=bgr.submat(roi);Imgproc.cvtColor(sub,gray,Imgproc.COLOR_BGR2GRAY);sub.release();Imgproc.GaussianBlur(gray,gray,new Size(5,5),0);Imgproc.Canny(gray,edges,40,120);Imgproc.findContours(edges,contours,hierarchy,Imgproc.RETR_LIST,Imgproc.CHAIN_APPROX_SIMPLE);Rect best=null;double bestScore=0;for(MatOfPoint c:contours){Rect q=Imgproc.boundingRect(c);double ar=q.width/(double)Math.max(1,q.height),wr=q.width/(double)scale,hr=q.height/(double)scale,area=Math.abs(Imgproc.contourArea(c))/Math.max(1.0,q.area());if(!plausibleDateApertureGeometry(ar,wr,hr))continue;double dx=(q.x+q.width/2.0-w/2.0)/w,dy=(q.y+q.height/2.0-h/2.0)/h,centre=1-Math.min(1,Math.hypot(dx,dy)*2.5),score=.45*centre+.30*Math.min(1,area/.65)+.25*(1-Math.min(1,Math.abs(ar-1.8)));if(score>bestScore){best=q;bestScore=score;}}if(best==null||bestScore<.52)return null;DateAperture d=new DateAperture();d.box=new Rect(x+best.x,y+best.y,best.width,best.height);d.confidence=bestScore;Mat ink=gray.submat(best);Mat bin=new Mat();Imgproc.threshold(ink,bin,0,255,Imgproc.THRESH_BINARY_INV+Imgproc.THRESH_OTSU);Moments m=Imgproc.moments(bin,true);if(m.m00>best.area()*.025&&m.m00<best.area()*.65){double nx=m.m10/m.m00,ny=m.m01/m.m00;d.numeralXPercent=(nx-best.width/2.0)/best.width*100;d.numeralYPercent=(ny-best.height/2.0)/best.height*100;d.numeralAvailable=numeralWithinAperture(d.numeralXPercent,d.numeralYPercent);}ink.release();bin.release();return d;}finally{for(MatOfPoint c:contours)c.release();rgba.release();bgr.release();gray.release();edges.release();hierarchy.release();}}
    static boolean plausibleDateApertureGeometry(double aspect,double widthRatio,double heightRatio){return Double.isFinite(aspect)&&Double.isFinite(widthRatio)&&Double.isFinite(heightRatio)&&aspect>=1.15&&aspect<=2.8&&widthRatio>=.12&&widthRatio<=.42&&heightRatio>=.07&&heightRatio<=.28;}
    static boolean numeralWithinAperture(double xPercent,double yPercent){return Double.isFinite(xPercent)&&Double.isFinite(yPercent)&&Math.abs(xPercent)<=45&&Math.abs(yPercent)<=45;}
    private static QcModuleResult.Confidence confidence(double s){return s>=.76?QcModuleResult.Confidence.HIGH:s>=.52?QcModuleResult.Confidence.MEDIUM:QcModuleResult.Confidence.LOW;}private static QcModuleResult.Confidence cap(QcModuleResult.Confidence a,QcModuleResult.Confidence b){return a.ordinal()>b.ordinal()?b:a;}private static Result unavailable(Bitmap w,String r){return new Result(w==null?null:w.copy(Bitmap.Config.ARGB_8888,false),"Extended GMT checks unavailable: "+r);}
}
