package com.watchalign.mobile;

import java.util.*;

/** Applies the production rectified metric to labelled controls and emits per-case and grouped distributions. */
final class TriangleControlSetRunner {
    static final class ControlCase {final String group,id,image;final PerspectiveMasterRenderer.Pose pose;final double[][] points;ControlCase(String g,String i,String imagePath,PerspectiveMasterRenderer.Pose p,double[][] q){group=g;id=i;image=imagePath;pose=p;points=q;}}
    static final class Output {final String casesCsv,distributionsCsv;Output(String c,String d){casesCsv=c;distributionsCsv=d;}}
    static Output run(List<ControlCase> controls){StringBuilder cases=new StringBuilder("group,id,image,base_to_60,apex_to_crown,rotation_deg,base_class,apex_class,rotation_class\n");Map<String,List<double[]>> groups=new TreeMap<>();for(ControlCase c:controls){Triangle12RelationalMetric.Result r=Triangle12RelationalMetric.measureRectifiedRaw(c.pose,c.points);if(r==null)throw new IllegalArgumentException("Invalid control geometry: "+c.id);cases.append(csv(c.group)).append(',').append(csv(c.id)).append(',').append(csv(c.image)).append(',').append(fmt(r.baseGapRatio)).append(',').append(fmt(r.apexGapRatio)).append(',').append(fmt(r.rotationDeg)).append(',').append(r.classification.baseTo60).append(',').append(r.classification.apexToCrown).append(',').append(r.classification.rotationMagnitude).append('\n');groups.computeIfAbsent(c.group,k->new ArrayList<>()).add(new double[]{r.baseGapRatio,r.apexGapRatio,r.rotationDeg});}StringBuilder dist=new StringBuilder("group,metric,n,mean,sd,median,min,max\n");for(Map.Entry<String,List<double[]>> e:groups.entrySet())for(int metric=0;metric<3;metric++){double[] v=new double[e.getValue().size()];for(int i=0;i<v.length;i++)v[i]=e.getValue().get(i)[metric];Arrays.sort(v);double mean=0;for(double x:v)mean+=x;mean/=v.length;double ss=0;for(double x:v)ss+=(x-mean)*(x-mean);double sd=Math.sqrt(ss/Math.max(1,v.length-1));dist.append(csv(e.getKey())).append(',').append(metric==0?"base_to_60":metric==1?"apex_to_crown":"rotation_deg").append(',').append(v.length).append(',').append(fmt(mean)).append(',').append(fmt(sd)).append(',').append(fmt(median(v))).append(',').append(fmt(v[0])).append(',').append(fmt(v[v.length-1])).append('\n');}return new Output(cases.toString(),dist.toString());}
    private static double median(double[]v){int n=v.length;return n%2==1?v[n/2]:(v[n/2-1]+v[n/2])/2;}private static String fmt(double v){return String.format(Locale.US,"%.6f",v);}private static String csv(String s){return '"'+s.replace("\"","\"\"")+'"';}private TriangleControlSetRunner(){}
}
