package com.watchalign.mobile;

import java.util.*;

/** Monte Carlo sensitivity analysis for operator point placement and perspective anchors. */
final class TriangleMetricValidation {
    static final class Sensitivity {final int samples;final double pointNoisePx,anchorNoisePx;final Stats baseTo60,apexToCrown,rotation;Sensitivity(int n,double p,double a,Stats b,Stats c,Stats r){samples=n;pointNoisePx=p;anchorNoisePx=a;baseTo60=b;apexToCrown=c;rotation=r;}String report(){return String.format(Locale.US,"samples=%d, point noise=±%.2f px, anchor noise=±%.2f px%nbase-to-60 |Δ| median %.5f, p95 %.5f, max %.5f%napex-to-crown |Δ| median %.5f, p95 %.5f, max %.5f%nrotation |Δ| median %.3f°, p95 %.3f°, max %.3f°",samples,pointNoisePx,anchorNoisePx,baseTo60.median,baseTo60.p95,baseTo60.max,apexToCrown.median,apexToCrown.p95,apexToCrown.max,rotation.median,rotation.p95,rotation.max);}}
    static final class Stats {final double median,p95,max;Stats(double m,double p,double x){median=m;p95=p;max=x;}}
    static Sensitivity analyse(PerspectiveMasterRenderer.Pose pose,double[][] points,int samples,double pointNoisePx,double anchorNoisePx,long seed){Triangle12RelationalMetric.Result baseline=Triangle12RelationalMetric.measureRectifiedRaw(pose,points);if(baseline==null)throw new IllegalArgumentException("Invalid baseline geometry");Random random=new Random(seed);double[] b=new double[samples],a=new double[samples],r=new double[samples];for(int i=0;i<samples;i++){PerspectiveMasterRenderer.Pose p=pose.copy();p.anchor12X+=noise(random,anchorNoisePx);p.anchor12Y+=noise(random,anchorNoisePx);p.anchor3X+=noise(random,anchorNoisePx);p.anchor3Y+=noise(random,anchorNoisePx);p.anchor6X+=noise(random,anchorNoisePx);p.anchor6Y+=noise(random,anchorNoisePx);p.anchor9X+=noise(random,anchorNoisePx);p.anchor9Y+=noise(random,anchorNoisePx);double[][] q=new double[5][2];for(int k=0;k<5;k++){q[k][0]=points[k][0]+noise(random,pointNoisePx);q[k][1]=points[k][1]+noise(random,pointNoisePx);}Triangle12RelationalMetric.Result x=Triangle12RelationalMetric.measureRectifiedRaw(p,q);b[i]=Math.abs(x.baseGapRatio-baseline.baseGapRatio);a[i]=Math.abs(x.apexGapRatio-baseline.apexGapRatio);r[i]=Math.abs(x.rotationDeg-baseline.rotationDeg);}return new Sensitivity(samples,pointNoisePx,anchorNoisePx,stats(b),stats(a),stats(r));}
    private static double noise(Random r,double bound){return (r.nextDouble()*2-1)*bound;}private static Stats stats(double[] v){Arrays.sort(v);return new Stats(percentile(v,.5),percentile(v,.95),v[v.length-1]);}private static double percentile(double[] v,double p){double x=p*(v.length-1);int lo=(int)Math.floor(x),hi=(int)Math.ceil(x);return v[lo]+(v[hi]-v[lo])*(x-lo);}private TriangleMetricValidation(){}
}
