package com.watchalign.mobile;

import org.junit.Test;import java.util.*;import static org.junit.Assert.*;

public class TriangleMetricValidationTest {
 @Test public void rawRectifiedMeasurementIsSeparateFromFrozenClassification(){PerspectiveMasterRenderer.Pose p=pose();Triangle12RelationalMetric.Result r=Triangle12RelationalMetric.measureRectifiedRaw(p,points(p,.169,.26,.10));assertNotNull(r.rawRectified);assertEquals(r.baseGapRatio,r.rawRectified.baseTo60Ratio,0);assertEquals(Triangle12RelationalMetric.RangePosition.WITHIN,r.classification.baseTo60);assertEquals(.10f,GenTriangle12RelationalReference.BASE_TO_60_MIN,0);assertEquals(.20f,GenTriangle12RelationalReference.BASE_TO_60_MAX,0);assertEquals(.18f,GenTriangle12RelationalReference.APEX_TO_CROWN_MIN,0);assertEquals(.34f,GenTriangle12RelationalReference.APEX_TO_CROWN_MAX,0);assertEquals(.50f,GenTriangle12RelationalReference.ROTATION_OBSERVED_GEN_MAX_DEG,0);}

 @Test public void realisticPointPerturbationReportsSensitivity(){PerspectiveMasterRenderer.Pose p=pose();double[][] q=points(p,.169,.26,.10);TriangleMetricValidation.Sensitivity s=TriangleMetricValidation.analyse(p,q,2000,.75,1.0,520013L);System.out.println("12-TRIANGLE REPEATABILITY\n"+s.report());assertTrue(s.baseTo60.p95<.04);assertTrue(s.apexToCrown.p95<.04);assertTrue(s.rotation.p95<2.5);}

 @Test public void controlRunnerOutputsGenuineAndReplicaDistributions(){PerspectiveMasterRenderer.Pose p=pose();List<TriangleControlSetRunner.ControlCase> c=new ArrayList<>();c.add(control("genuine","gen-1",p,.163,.25,.10));c.add(control("genuine","gen-2",p,.169,.26,-.20));c.add(control("genuine","gen-3",p,.190,.29,.42));c.add(control("replica","rep-1",p,.070,.39,1.40));c.add(control("replica","rep-2",p,.075,.38,1.20));c.add(control("replica","rep-3",p,.080,.40,1.60));TriangleControlSetRunner.Output out=TriangleControlSetRunner.run(c);System.out.println("12-TRIANGLE CONTROL DISTRIBUTIONS\n"+out.distributionsCsv);assertTrue(out.casesCsv.contains("\"genuine\""));assertTrue(out.casesCsv.contains("\"replica\""));assertTrue(out.distributionsCsv.contains("base_to_60"));assertTrue(out.distributionsCsv.contains("apex_to_crown"));assertTrue(out.distributionsCsv.contains("rotation_deg"));}

 private static TriangleControlSetRunner.ControlCase control(String group,String id,PerspectiveMasterRenderer.Pose p,double base,double apex,double rotation){return new TriangleControlSetRunner.ControlCase(group,id,id+".jpg",p.copy(),points(p,base,apex,rotation));}
 private static PerspectiveMasterRenderer.Pose pose(){PerspectiveMasterRenderer.Pose p=new PerspectiveMasterRenderer.Pose();p.anchorMode=true;p.perspectiveMode=true;p.anchor12X=510;p.anchor12Y=160;p.anchor3X=860;p.anchor3Y=520;p.anchor6X=500;p.anchor6Y=900;p.anchor9X=175;p.anchor9Y=545;return p;}
 private static double[][] points(PerspectiveMasterRenderer.Pose p,double baseGap,double apexGap,double rotation){double bw=.25,baseY=-.72,apexY=-.37,rad=Math.toRadians(rotation),dx=Math.cos(rad)*bw,dy=-Math.sin(rad)*bw;double[][] dial={{-dx/2,baseY-dy/2},{dx/2,baseY+dy/2},{0,apexY},{0,baseY-baseGap*bw},{0,apexY+apexGap*bw}};double[][] image=new double[5][2];for(int i=0;i<5;i++)image[i]=PerspectiveRectifier.projectRaw(p,dial[i][0],dial[i][1]);return image;}
}
