"""Watch Align launcher icon (alpha65): one geometry, written as Android vector drawables and an SVG preview.

python3 tools/icon/make_icon.py  -> android/app/src/main/res/drawable/ic_launcher_{foreground,monochrome}.xml
                                     tools/icon/icon_preview.svg (and .png when cairosvg is installed)
Design: a dial seen straight on, twelve hour ticks, the 12 index as a lume triangle under a cyan
reference line (the app measures each marker against the minute ticks either side), and the app's
green "nothing flagged" badge. Original artwork; no watch brand marks.
"""
import math, os

NAVY, FACE, STEEL, TICK, LUME, CYAN, GREEN, WHITE = '#0B1628', '#060B13', '#C9D3DE', '#DCE4EC', '#F1F4E6', '#32D5F2', '#28D278', '#FFFFFF'
C = 54.0                      # adaptive icon: 108 x 108 viewport, content inside the 66 dp safe circle

def circle(cx, cy, r):
    return f'M{cx - r:.2f},{cy:.2f}a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0Z'

def clock(deg, r):
    t = math.radians(deg); return C + r * math.sin(t), C - r * math.cos(t)

ticks = []
for h in range(1, 12):
    r0 = 22.5 if h in (3, 6, 9) else 24.5
    (x0, y0), (x1, y1) = clock(h * 30, r0), clock(h * 30, 28.0)
    ticks.append(f'M{x0:.2f},{y0:.2f}L{x1:.2f},{y1:.2f}')
TRI = 'M48,33L60,33L54,43.4Z'
CHORD = 'M47.2,29.6L60.8,29.6'
DOTS = circle(47.2, 29.6, 1.45) + circle(60.8, 29.6, 1.45)
BX, BY, BR = 71.5, 71.5, 10.5
CHECK = f'M{BX - 5.2:.2f},{BY + 0.2:.2f}L{BX - 1.4:.2f},{BY + 3.9:.2f}L{BX + 5.4:.2f},{BY - 3.6:.2f}'

# (kind, path, colour, stroke width); kind fill or stroke
LAYERS = [
    ('fill', circle(C, C, 30.5), STEEL, 0),
    ('fill', circle(C, C, 28.9), FACE, 0),
    ('stroke', ''.join(ticks), TICK, 1.7),
    ('fill', TRI, LUME, 0),
    ('stroke', CHORD, CYAN, 1.2),
    ('fill', DOTS, CYAN, 0),
    ('fill', circle(BX, BY, BR + 2.2), FACE, 0),
    ('fill', circle(BX, BY, BR), GREEN, 0),
    ('stroke', CHECK, WHITE, 2.6),
]
# Themed (monochrome) icon: outlines only, one colour. The layer is a mask, so the badge can't
# cover the dial; the ring stops short of the badge and the 4 and 5 ticks are left out instead.
def ring_gap(r, gap_clock, clear):
    bd = math.hypot(BX - C, BY - C)
    # Angular half-width of the ring inside `clear` of the badge centre (law of cosines).
    half = math.degrees(math.acos((r * r + bd * bd - clear * clear) / (2 * r * bd)))
    (x0, y0), (x1, y1) = clock(gap_clock + half, r), clock(gap_clock - half + 360, r)
    return f'M{x0:.2f},{y0:.2f}A{r:.2f},{r:.2f} 0 1,1 {x1:.2f},{y1:.2f}'
mono_ticks = ''.join(t for h, t in zip(range(1, 12), ticks) if h not in (4, 5))
MONO = [
    ('stroke', ring_gap(29.7, 135, BR + 3.2), WHITE, 1.8),
    ('stroke', mono_ticks, WHITE, 1.7),
    ('fill', TRI, WHITE, 0),
    ('stroke', CHORD, WHITE, 1.2),
    ('stroke', circle(BX, BY, BR), WHITE, 2.0),
    ('stroke', CHECK, WHITE, 2.6),
]

def vector(layers):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/icon/make_icon.py; edit the script, not this file. -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="108dp" android:height="108dp"',
           '    android:viewportWidth="108" android:viewportHeight="108">']
    for kind, d, col, w in layers:
        if kind == 'fill':
            out.append(f'    <path android:fillColor="{col}" android:pathData="{d}"/>')
        else:
            out.append(f'    <path android:strokeColor="{col}" android:strokeWidth="{w}" android:strokeLineCap="round"'
                       f' android:strokeLineJoin="round" android:fillColor="#00000000" android:pathData="{d}"/>')
    out.append('</vector>')
    return '\n'.join(out) + '\n'

def svg(layers, background=True, mask=True):
    body = []
    for kind, d, col, w in layers:
        if kind == 'fill': body.append(f'<path fill="{col}" d="{d}"/>')
        else: body.append(f'<path fill="none" stroke="{col}" stroke-width="{w}" stroke-linecap="round" stroke-linejoin="round" d="{d}"/>')
    clip = '<clipPath id="m"><circle cx="54" cy="54" r="36"/></clipPath>' if mask else ''
    bg = f'<rect width="108" height="108" fill="{NAVY}"/>' if background else ''
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="432" height="432"><defs>{clip}</defs>'
            f'<g clip-path="url(#m)">{bg}{"".join(body)}</g></svg>')

if __name__ == '__main__':
    root = os.path.join(os.path.dirname(__file__), '..', '..')
    res = os.path.join(root, 'android/app/src/main/res')
    os.makedirs(os.path.join(res, 'drawable'), exist_ok=True)
    open(os.path.join(res, 'drawable/ic_launcher_foreground.xml'), 'w').write(vector(LAYERS))
    open(os.path.join(res, 'drawable/ic_launcher_monochrome.xml'), 'w').write(vector(MONO))
    here = os.path.dirname(__file__)
    open(os.path.join(here, 'icon_preview.svg'), 'w').write(svg(LAYERS))
    try:
        import cairosvg
        cairosvg.svg2png(bytestring=svg(LAYERS).encode(), write_to=os.path.join(here, 'icon_preview.png'))
        cairosvg.svg2png(bytestring=svg(MONO).replace(NAVY, '#DDE3EA').replace('#FFFFFF', '#1D3A5F').encode(), write_to=os.path.join(here, 'icon_preview_themed.png'))
    except ImportError:
        pass
    print('written')
