package com.watchalign.mobile;

import android.content.Context;import android.graphics.Bitmap;import android.graphics.Color;import android.graphics.PointF;import android.hardware.camera2.CameraCharacteristics;import android.hardware.camera2.CameraManager;import android.util.Size;import androidx.core.content.FileProvider;import androidx.test.core.app.ApplicationProvider;import org.junit.Test;import java.io.File;import java.util.List;import static org.junit.Assert.*;

/** Physical-device smoke path for Camera2 capabilities and capture-to-history-to-export storage. */
public class CaptureHistoryExportDeviceTest {
 @Test public void rearCameraProvidesSuitableJpegStillStream()throws Exception{Context c=ApplicationProvider.getApplicationContext();CameraManager manager=(CameraManager)c.getSystemService(Context.CAMERA_SERVICE);boolean checked=false;for(String id:manager.getCameraIdList()){CameraCharacteristics cc=manager.getCameraCharacteristics(id);Integer facing=cc.get(CameraCharacteristics.LENS_FACING);if(facing==null||facing!=CameraCharacteristics.LENS_FACING_BACK)continue;Size[] sizes=cc.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP).getOutputSizes(android.graphics.ImageFormat.JPEG);Size selected=CameraCaptureConfig.chooseStill(sizes);assertTrue(selected.getWidth()>=1920);assertTrue(selected.getHeight()>=1080);assertTrue((long)selected.getWidth()*selected.getHeight()<=CameraCaptureConfig.MAX_STILL_PIXELS);checked=true;break;}assertTrue("A rear JPEG camera stream is required for guided capture",checked);}

 @Test public void capturedBitmapPersistsReopensAndExports()throws Exception{Context c=ApplicationProvider.getApplicationContext();Bitmap image=Bitmap.createBitmap(800,1000,Bitmap.Config.ARGB_8888);image.eraseColor(Color.DKGRAY);InspectionImageStore.setCaptured(image);assertSame(image,InspectionImageStore.takeCaptured());PerspectiveMasterRenderer.Pose p=new PerspectiveMasterRenderer.Pose();p.anchorMode=true;p.perspectiveMode=true;p.anchor12X=400;p.anchor12Y=100;p.anchor3X=700;p.anchor3Y=500;p.anchor6X=400;p.anchor6Y=900;p.anchor9X=100;p.anchor9Y=500;p.centerX=400;p.centerY=500;PointF[] points={new PointF(350,180),new PointF(450,180),new PointF(400,120),new PointF(400,90),new PointF(400,70)};Triangle12RelationalMetric.Result metric=new Triangle12RelationalMetric.Result(.169f,.26f,1.4f,.1f,0);InspectionHistory.Record saved=InspectionHistory.save(c,image,"126710BLNR",p,points,metric,"device smoke result");assertTrue(new File(saved.imagePath).isFile());List<InspectionHistory.Record> records=InspectionHistory.list(c);assertFalse(records.isEmpty());assertTrue(InspectionHistory.reopen(records.get(0)));File export=QcExport.createExportFile(c,image,"126710BLNR","device smoke result");assertTrue(export.length()>0);assertNotNull(FileProvider.getUriForFile(c,c.getPackageName()+".files",export));image.recycle();}
}
