package com.watchalign.mobile;

import android.content.Context;import androidx.test.core.app.ApplicationProvider;import org.junit.Test;import java.io.*;import java.util.*;import static org.junit.Assert.*;

/** Runs a user-supplied labelled image/point manifest through the production metric on device. */
public class TriangleControlSetDeviceRunnerTest {
 @Test public void runExternalControlSet()throws Exception{Context c=ApplicationProvider.getApplicationContext();File dir=new File(c.getExternalFilesDir(null),"triangle-validation"),manifest=new File(dir,"controls.csv");assertTrue("Place controls.csv and its referenced images in "+dir.getAbsolutePath(),manifest.isFile());List<TriangleControlSetRunner.ControlCase> controls=new ArrayList<>();try(BufferedReader reader=new BufferedReader(new FileReader(manifest))){String line;boolean header=true;while((line=reader.readLine())!=null){if(header){header=false;continue;}if(line.trim().isEmpty())continue;String[] v=line.split(",",-1);assertEquals("Expected 21 CSV columns",21,v.length);File image=new File(dir,v[2]);assertTrue("Missing control image "+image,image.isFile());PerspectiveMasterRenderer.Pose p=new PerspectiveMasterRenderer.Pose();p.anchorMode=true;p.perspectiveMode=true;p.anchor12X=f(v[3]);p.anchor12Y=f(v[4]);p.anchor3X=f(v[5]);p.anchor3Y=f(v[6]);p.anchor6X=f(v[7]);p.anchor6Y=f(v[8]);p.anchor9X=f(v[9]);p.anchor9Y=f(v[10]);double[][] points=new double[5][2];for(int i=0;i<5;i++){points[i][0]=f(v[11+i*2]);points[i][1]=f(v[12+i*2]);}controls.add(new TriangleControlSetRunner.ControlCase(v[0],v[1],image.getName(),p,points));}}assertTrue("Use multiple controls",controls.size()>=4);TriangleControlSetRunner.Output out=TriangleControlSetRunner.run(controls);write(new File(dir,"measurements.csv"),out.casesCsv);write(new File(dir,"distributions.csv"),out.distributionsCsv);System.out.println(out.distributionsCsv);}
 private static float f(String s){return Float.parseFloat(s.trim());}private static void write(File f,String s)throws Exception{try(FileWriter w=new FileWriter(f)){w.write(s);}}
}
