#!/usr/bin/env python3
"""RESEARCH -> APP. Generate android/.../Alpha99Uncertainty.java from alpha99_uncertainty.properties (written by
measurement_uncertainty.py from genuine photos only). Alpha99FindingsTest pins the generated constants to that file."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA = os.path.join(HERE, '..', '..', '..', 'android/app/src/main/java/com/watchalign/mobile/Alpha99Uncertainty.java')


def main():
    p = {k.strip(): v.strip() for k, v in (l.split('=', 1) for l in open(os.path.join(HERE, 'alpha99_uncertainty.properties'))
                                          if '=' in l and not l.startswith('#'))}
    out = ['package com.watchalign.mobile;', '',
           '/**',
           ' * GENERATED by tools/research/alpha96_calibration/gen_alpha99_constants.py - do not edit by hand.',
           ' * Single-photo measurement uncertainty per feature family: the pooled within-watch standard deviation over',
           ' * genuine physical watches photographed two or more times (no replica or test photo involved). Source:',
           ' * measurement_uncertainty.py -> alpha99_uncertainty.properties, results/alpha99/uncertainty.md.',
           ' * *_R in dial radii, *_PX in pixels (positional families: the app uses max(sigma_R, sigma_PX / photo R)), *_DEG in',
           ' * degrees. K_SIGMA: a reading beyond the genuine maximum is a clear finding only when the excess exceeds K sigma.',
           ' */',
           'final class Alpha99Uncertainty {',
           '    private Alpha99Uncertainty(){}',
           f"    static final double K_SIGMA={float(p['k_sigma'])};"]
    for k in sorted(p):
        if k == 'k_sigma' or k.endswith('.watches'):
            continue
        fam, unit = k.split('.')
        out.append(f'    /** {p[k + ".watches"]} genuine watches. */')
        out.append(f'    static final double {fam.upper()}_{unit.upper()}={p[k]};')
    out.append('}')
    open(JAVA, 'w').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
