#!/usr/bin/env python3
"""RESEARCH -> APP. Generate android/.../Alpha98Reference.java from alpha98_reference.csv and alpha98_nominal.properties
(written by build_alpha98_reference.py). Alpha98ReferenceTest pins the generated constants to those files."""
import csv
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
JAVA = os.path.join(HERE, '..', '..', '..', 'android/app/src/main/java/com/watchalign/mobile/Alpha98Reference.java')
FEATURES = ('six_rot', 'six_off', 'nine_rot', 'nine_off', 'rounds_off', 'ring_rot', 'ring_shift', 'date_tilt')
CONST = {'six_rot': 'SIX_ROT', 'six_off': 'SIX_OFF', 'nine_rot': 'NINE_ROT', 'nine_off': 'NINE_OFF', 'rounds_off': 'ROUNDS_OFF',
         'ring_rot': 'RING_ROT', 'ring_shift': 'RING_SHIFT', 'date_tilt': 'DATE_TILT'}


def arr(vals):
    return '{\n' + ',\n'.join('            ' + ','.join(vals[i:i + 8]) for i in range(0, len(vals), 8)) + '}'


def main():
    nom = {k.strip(): v.strip() for k, v in (l.split('=', 1) for l in open(os.path.join(HERE, 'alpha98_nominal.properties')) if '=' in l and not l.startswith('#'))}
    ref = defaultdict(list)
    for r in csv.DictReader(open(os.path.join(HERE, 'alpha98_reference.csv'))):
        ref[r['feature']].append((r['far'], r['dial_radius_px'] or 'NaN'))
    out = ['package com.watchalign.mobile;', '',
           '/**',
           ' * GENERATED by tools/research/alpha96_calibration/gen_alpha98_constants.py - do not edit by hand.',
           ' * Genuine reference for the Alpha98 results screen: per physical watch, how far that watch reads from the genuine',
           ' * nominal (signed features: |value - nominal without that watch|; magnitudes: |value|), and its dial radius in px.',
           ' * 6, 9, rounds, ring: catalogue minus SWE + owner-priority official / CPO watches. Date-window tilt: catalogue',
           ' * including SWE + owner priority. Shared / stock photos excluded; one value per watch. See build_alpha98_reference.py.',
           ' */',
           'final class Alpha98Reference {',
           '    private Alpha98Reference(){}']
    for k in ('six_rot', 'nine_rot', 'ring_rot', 'date_tilt'):
        out.append(f'    static final double NOMINAL_{CONST[k]}={nom[k]};')
    for k in FEATURES:
        out.append(f'    static final double[] {CONST[k]}_FAR={arr([f for f, _ in ref[k]])};')
        out.append(f'    static final double[] {CONST[k]}_R={arr([r if r != "NaN" else "Double.NaN" for _, r in ref[k]])};')
    out.append('}')
    open(JAVA, 'w').write('\n'.join(out) + '\n')
    print('generated', os.path.relpath(JAVA), {k: len(ref[k]) for k in FEATURES})


if __name__ == '__main__':
    main()
